# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Notepad.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(610, 380)
        mainWindow.setMinimumSize(QtCore.QSize(610, 380))
        mainWindow.setMaximumSize(QtCore.QSize(610, 380))
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 30, 261, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.field_note = QtWidgets.QTextEdit(self.centralwidget)
        self.field_note.setGeometry(QtCore.QRect(10, 80, 261, 191))
        self.field_note.setObjectName("field_note")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.label_title.setObjectName("label_title")
        self.label_note = QtWidgets.QLabel(self.centralwidget)
        self.label_note.setGeometry(QtCore.QRect(10, 60, 47, 13))
        self.label_note.setObjectName("label_note")
        self.label_notes = QtWidgets.QLabel(self.centralwidget)
        self.label_notes.setGeometry(QtCore.QRect(300, 60, 91, 16))
        self.label_notes.setObjectName("label_notes")
        self.table_notes = QtWidgets.QTableWidget(self.centralwidget)
        self.table_notes.setGeometry(QtCore.QRect(300, 80, 291, 192))
        self.table_notes.setObjectName("table_notes")
        self.table_notes.setColumnCount(2)
        self.table_notes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_notes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_notes.setHorizontalHeaderItem(1, item)
        self.btn_create = QtWidgets.QPushButton(self.centralwidget)
        self.btn_create.setEnabled(True)
        self.btn_create.setGeometry(QtCore.QRect(200, 300, 75, 23))
        self.btn_create.setStyleSheet("")
        self.btn_create.setObjectName("btn_create")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(430, 300, 170, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_edit = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_edit.setObjectName("btn_edit")
        self.horizontalLayout.addWidget(self.btn_edit)
        self.btn_del = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_del.setObjectName("btn_del")
        self.horizontalLayout.addWidget(self.btn_del)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 610, 21))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Записная книжка"))
        self.label_title.setText(_translate("mainWindow", "Заголовок"))
        self.label_note.setText(_translate("mainWindow", "Заметка"))
        self.label_notes.setText(_translate("mainWindow", "Таблица заметок"))
        item = self.table_notes.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "Title"))
        item = self.table_notes.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "Date & Time"))
        self.btn_create.setText(_translate("mainWindow", "Создать"))
        self.btn_edit.setText(_translate("mainWindow", "Редактировать"))
        self.btn_del.setText(_translate("mainWindow", "Удалить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
